Grouping

뉴욕 airBnB : https://www.kaggle.com/ptoscano230382/air-bnb-ny-2019 DataUrl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv’

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')
df

id                                               name   host_id  \
0          2539                 Clean & quiet apt home by the park      2787   
1          2595                              Skylit Midtown Castle      2845   
2          3647                THE VILLAGE OF HARLEM....NEW YORK !      4632   
3          3831                    Cozy Entire Floor of Brownstone      4869   
4          5022   Entire Apt: Spacious Studio/Loft by central park      7192   
...         ...                                                ...       ...   
48890  36484665    Charming one bedroom - newly renovated rowhouse   8232441   
48891  36485057      Affordable room in Bushwick/East Williamsburg   6570630   
48892  36485431            Sunny Studio at Historical Neighborhood  23492952   
48893  36485609               43rd St. Time Square-cozy single bed  30985759   
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen  68119814   

           host_name neighbourhood_group       neighbourhood  latitude  \
0               John            Brooklyn          Kensington  40.64749   
1           Jennifer           Manhattan             Midtown  40.75362   
2          Elisabeth           Manhattan              Harlem  40.80902   
3        LisaRoxanne            Brooklyn        Clinton Hill  40.68514   
4              Laura           Manhattan         East Harlem  40.79851   
...              ...                 ...                 ...       ...   
48890        Sabrina            Brooklyn  Bedford-Stuyvesant  40.67853   
48891        Marisol            Brooklyn            Bushwick  40.70184   
48892  Ilgar & Aysel           Manhattan              Harlem  40.81475   
48893            Taz           Manhattan      Hell's Kitchen  40.75751   
48894     Christophe           Manhattan      Hell's Kitchen  40.76404   

       longitude        room_type  price  minimum_nights  number_of_reviews  \
0      -73.97237     Private room    149               1                  9   
1      -73.98377  Entire home/apt    225               1                 45   
2      -73.94190     Private room    150               3                  0   
3      -73.95976  Entire home/apt     89               1                270   
4      -73.94399  Entire home/apt     80              10                  9   
...          ...              ...    ...             ...                ...   
48890  -73.94995     Private room     70               2                  0   
48891  -73.93317     Private room     40               4                  0   
48892  -73.94867  Entire home/apt    115              10                  0   
48893  -73.99112      Shared room     55               1                  0   
48894  -73.98933     Private room     90               7                  0   

      last_review  reviews_per_month  calculated_host_listings_count  \
0      2018-10-19               0.21                               6   
1      2019-05-21               0.38                               2   
2             NaN                NaN                               1   
3      2019-07-05               4.64                               1   
4      2018-11-19               0.10                               1   
...           ...                ...                             ...   
48890         NaN                NaN                               2   
48891         NaN                NaN                               2   
48892         NaN                NaN                               1   
48893         NaN                NaN                               6   
48894         NaN                NaN                               1   

       availability_365  
0                   365  
1                   355  
2                   365  
3                   194  
4                     0  
...                 ...  
48890                 9  
48891                36  
48892                27  
48893                 2  
48894                23  

[48895 rows x 16 columns]

데이터의 각 host_name의 빈도수를 구하고 host_name으로 정렬하여 상위 5개를 출력하라

In [6]:
df.host_name.value_counts().sort_index().head(5)

'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
Name: host_name, dtype: int64

데이터의 각 host_name의 빈도수를 구하고 빈도수 기준 내림차순 정렬한 데이터 프레임을 만들어라. 빈도수 컬럼은 counts로 명명하라

In [17]:
ddf = df.host_name.value_counts().to_frame()
ddf.columns = ['counts']

In [18]:
ddf

counts
Michael               417
David                 403
Sonder (NYC)          327
John                  294
Alex                  279
...                   ...
Rhonycs                 1
Brandy-Courtney         1
Shanthony               1
Aurore And Jamila       1
Ilgar & Aysel           1

[11452 rows x 1 columns]

neighbourhood_group의 값에 따른 neighbourhood컬럼 값의 갯수를 구하여라

In [19]:
df.neighbourhood_group.value_counts()

Manhattan        21661
Brooklyn         20104
Queens            5666
Bronx             1091
Staten Island      373
Name: neighbourhood_group, dtype: int64

In [24]:
df.groupby(['neighbourhood_group', 'neighbourhood'], as_index = False).size()

neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

neighbourhood_group의 값에 따른 neighbourhood컬럼 값 중 neighbourhood_group그룹의 최댓값들을 출력하라

In [31]:
df.groupby(['neighbourhood_group', 'neighbourhood']).size().groupby('neighbourhood_group').max()

neighbourhood_group
Bronx              70
Brooklyn         3920
Manhattan        2658
Queens            900
Staten Island      48
dtype: int64

neighbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값을 구하여라

In [41]:
df[['neighbourhood_group', 'price']].groupby('neighbourhood_group').agg(['mean','var','max','min'])

price                         
                           mean           var    max min
neighbourhood_group                                     
Bronx                 87.496792  11386.885081   2500   0
Brooklyn             124.383207  34921.719135  10000   0
Manhattan            196.875814  84904.159185  10000   0
Queens                99.517649  27923.130227  10000  10
Staten Island        114.812332  77073.088342   5000  13

neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 구하라

In [43]:
df[['neighbourhood', 'neighbourhood_group', 'price']].groupby(['neighbourhood', 'neighbourhood_group']).mean()

price
neighbourhood   neighbourhood_group            
Allerton        Bronx                 87.595238
Arden Heights   Staten Island         67.250000
Arrochar        Staten Island        115.000000
Arverne         Queens               171.779221
Astoria         Queens               117.187778
...                                         ...
Windsor Terrace Brooklyn             138.993631
Woodhaven       Queens                67.170455
Woodlawn        Bronx                 60.090909
Woodrow         Staten Island        700.000000
Woodside        Queens                85.097872

[221 rows x 1 columns]

데이터중 neighbourhood_group 값에 따른 room_type 컬럼의 숫자를 구하고 neighbourhood_group 값을 기준으로 각 값의 비율을 구하여라

In [53]:
ans = df.groupby(['neighbourhood_group', 'room_type']).size().unstack()
ans

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group                                            
Bronx                            379           652           60
Brooklyn                        9559         10132          413
Manhattan                      13199          7982          480
Queens                          2096          3372          198
Staten Island                    176           188            9

In [62]:
ans.values

array([[  379,   652,    60],
       [ 9559, 10132,   413],
       [13199,  7982,   480],
       [ 2096,  3372,   198],
       [  176,   188,     9]], dtype=int64)

In [65]:
ans.sum(axis = 1).values.reshape(-1,1)

array([[ 1091],
       [20104],
       [21661],
       [ 5666],
       [  373]], dtype=int64)

In [67]:
ans.loc[:,:] = ans.values / ans.sum(axis = 1).values.reshape(-1,1)

In [68]:
ans

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group                                            
Bronx                       0.347388      0.597617     0.054995
Brooklyn                    0.475478      0.503979     0.020543
Manhattan                   0.609344      0.368496     0.022160
Queens                      0.369926      0.595129     0.034945
Staten Island               0.471850      0.504021     0.024129

## Timeseries

주가 데이터 : https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data DataUrl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv’

In [122]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv')
df

Yr_Mo_Dy    RPT    VAL    ROS    KIL    SHA    BIR    DUB    CLA  \
0     2061-01-01  15.04  14.96  13.17   9.29    NaN   9.87  13.67  10.25   
1     2061-01-02  14.71    NaN  10.83   6.50  12.62   7.67  11.50  10.04   
2     2061-01-03  18.50  16.88  12.33  10.13  11.17   6.17  11.25    NaN   
3     2061-01-04  10.58   6.63  11.75   4.58   4.54   2.88   8.63   1.79   
4     2061-01-05  13.33  13.25  11.42   6.17  10.71   8.21  11.92   6.54   
...          ...    ...    ...    ...    ...    ...    ...    ...    ...   
6569  1978-12-27  17.58  16.96  17.62   8.08  13.21  11.67  14.46  15.59   
6570  1978-12-28  13.21   5.46  13.46   5.00   8.12   9.42  14.33  16.25   
6571  1978-12-29  14.00  10.29  14.42   8.71   9.71  10.54  19.17  12.46   
6572  1978-12-30  18.50  14.04  21.29   9.13  12.75   9.71  18.08  12.87   
6573  1978-12-31  20.33  17.41  27.29   9.59  12.08  10.13  19.25  11.63   

        MUL    CLO    BEL    MAL  
0     10.83  12.58  18.50  15.04  
1      9.79   9.67  17.54  13.83  
2      8.50   7.67  12.75  12.71  
3      5.83   5.88   5.46  10.88  
4     10.92  10.34  12.92  11.83  
...     ...    ...    ...    ...  
6569  14.04  14.00  17.21  40.08  
6570  15.25  18.05  21.79  41.46  
6571  14.50  16.42  18.88  29.58  
6572  12.46  12.12  14.67  28.79  
6573  11.58  11.38  12.08  22.08  

[6574 rows x 13 columns]

In [123]:
df['Yr_Mo_Dy'] = pd.to_datetime(df['Yr_Mo_Dy'])
df['Yr_Mo_Dy']

0      2061-01-01
1      2061-01-02
2      2061-01-03
3      2061-01-04
4      2061-01-05
          ...    
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

Yr_Mo_Dy에 존재하는 년도의 유일값을 모두 출력하라

In [124]:
df['Yr_Mo_Dy'].dt.year.drop_duplicates().values

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978], dtype=int64)

In [125]:
df.Yr_Mo_Dy.dt.year.unique()

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978], dtype=int64)

Yr_Mo_Dy에 년도가 2061년 이상의 경우에는 모두 잘못된 데이터이다. 해당경우의 값은 100을 빼서 새롭게 날짜를 Yr_Mo_Dy 컬럼에 정의하라

In [126]:
df[df['Yr_Mo_Dy'].dt.year > 2061].Yr_Mo_Dy.dt.year.values

array([2062, 2062, 2062, ..., 2070, 2070, 2070], dtype=int64)

In [127]:
years = df[df['Yr_Mo_Dy'].dt.year > 2061].Yr_Mo_Dy.dt.year.values

In [128]:
years_values = years - 100
years_values

array([1962, 1962, 1962, ..., 1970, 1970, 1970], dtype=int64)

In [156]:
df['Yr_Mo_Dy'].dt.month

0        1
1        1
2        1
3        1
4        1
        ..
6569    12
6570    12
6571    12
6572    12
6573    12
Name: Yr_Mo_Dy, Length: 6574, dtype: int64

In [147]:
import datetime

In [159]:
def fix_century(x):
    import datetime
    
    year = x.year - 100 if x.year >= 2061 else x.year
    return pd.to_datetime(datetime.date(year, x.month, x.day))


df['Yr_Mo_Dy'] = df['Yr_Mo_Dy'].apply(fix_century)

Ans = df.head(4)

In [160]:
df

Yr_Mo_Dy    RPT    VAL    ROS    KIL    SHA    BIR    DUB    CLA  \
0    1961-01-01  15.04  14.96  13.17   9.29    NaN   9.87  13.67  10.25   
1    1961-01-02  14.71    NaN  10.83   6.50  12.62   7.67  11.50  10.04   
2    1961-01-03  18.50  16.88  12.33  10.13  11.17   6.17  11.25    NaN   
3    1961-01-04  10.58   6.63  11.75   4.58   4.54   2.88   8.63   1.79   
4    1961-01-05  13.33  13.25  11.42   6.17  10.71   8.21  11.92   6.54   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
6569 1978-12-27  17.58  16.96  17.62   8.08  13.21  11.67  14.46  15.59   
6570 1978-12-28  13.21   5.46  13.46   5.00   8.12   9.42  14.33  16.25   
6571 1978-12-29  14.00  10.29  14.42   8.71   9.71  10.54  19.17  12.46   
6572 1978-12-30  18.50  14.04  21.29   9.13  12.75   9.71  18.08  12.87   
6573 1978-12-31  20.33  17.41  27.29   9.59  12.08  10.13  19.25  11.63   

        MUL    CLO    BEL    MAL  
0     10.83  12.58  18.50  15.04  
1      9.79   9.67  17.54  13.83  
2      8.50   7.67  12.75  12.71  
3      5.83   5.88   5.46  10.88  
4     10.92  10.34  12.92  11.83  
...     ...    ...    ...    ...  
6569  14.04  14.00  17.21  40.08  
6570  15.25  18.05  21.79  41.46  
6571  14.50  16.42  18.88  29.58  
6572  12.46  12.12  14.67  28.79  
6573  11.58  11.38  12.08  22.08  

[6574 rows x 13 columns]

In [171]:
df.groupby(df.Yr_Mo_Dy.dt.year).mean()

RPT        VAL        ROS       KIL        SHA       BIR  \
Yr_Mo_Dy                                                                   
1961      12.299583  10.351796  11.362369  6.958227  10.881763  7.729726   
1962      12.246923  10.110438  11.732712  6.960440  10.657918  7.393068   
1963      12.813452  10.836986  12.541151  7.330055  11.724110  8.434712   
1964      12.363661  10.920164  12.104372  6.787787  11.454481  7.570874   
1965      12.451370  11.075534  11.848767  6.858466  11.024795  7.478110   
1966      13.461973  11.557205  12.020630  7.345726  11.805041  7.793671   
1967      12.737151  10.990986  11.739397  7.143425  11.630740  7.368164   
1968      11.835628  10.468197  11.409754  6.477678  10.760765  6.067322   
1969      11.166356   9.723699  10.902000  5.767973   9.873918  6.189973   
1970      12.600329  10.726932  11.730247  6.217178  10.567370  7.609452   
1971      11.273123   9.095178  11.088329  5.241507   9.440329  6.097151   
1972      12.463962  10.561311  12.058333  5.929699   9.430410  6.358825   
1973      11.828466  10.680493  10.680493  5.547863   9.640877  6.548740   
1974      13.643096  11.811781  12.336356  6.427041  11.110986  6.809781   
1975      12.008575  10.293836  11.564712  5.269096   9.190082  5.668521   
1976      11.737842  10.203115  10.761230  5.109426   8.846339  6.311038   
1977      13.099616  11.144493  12.627836  6.073945  10.003836  8.586438   
1978      12.504356  11.044274  11.380000  6.082356  10.167233  7.650658   

                DUB        CLA       MUL        CLO        BEL        MAL  
Yr_Mo_Dy                                                                   
1961       9.733923   8.858788  8.647652   9.835577  13.502795  13.680773  
1962      11.020712   8.793753  8.316822   9.676247  12.930685  14.323956  
1963      11.075699  10.336548  8.903589  10.224438  13.638877  14.999014  
1964      10.259153   9.467350  7.789016  10.207951  13.740546  14.910301  
1965      10.618712   8.879918  7.907425   9.918082  12.964247  15.591644  
1966      10.579808   8.835096  8.514438   9.768959  14.265836  16.307260  
1967      10.652027   9.325616  8.645014   9.547425  14.774548  17.135945  
1968       8.859180   8.255519  7.224945   7.832978  12.808634  15.017486  
1969       8.564493   7.711397  7.924521   7.754384  12.621233  15.762904  
1970       9.609890   8.334630  9.297616   8.289808  13.183644  16.456027  
1971       8.385890   6.757315  7.915370   7.229753  12.208932  15.025233  
1972       9.704508   7.680792  8.357295   7.515273  12.727377  15.028716  
1973       8.482110   7.614274  8.245534   7.812411  12.169699  15.441096  
1974      10.084603   9.896986  9.331753   8.736356  13.252959  16.947671  
1975       8.562603   7.843836  8.797945   7.382822  12.631671  15.307863  
1976       9.149126   7.146202  8.883716   7.883087  12.332377  15.471448  
1977      11.523205   8.378384  9.098192   8.821616  13.459068  16.590849  
1978       9.489342   8.800466  9.089753   8.301699  12.967397  16.771370

In [172]:
df['weekday'] = df.Yr_Mo_Dy.dt.weekday
df

Yr_Mo_Dy    RPT    VAL    ROS    KIL    SHA    BIR    DUB    CLA  \
0    1961-01-01  15.04  14.96  13.17   9.29    NaN   9.87  13.67  10.25   
1    1961-01-02  14.71    NaN  10.83   6.50  12.62   7.67  11.50  10.04   
2    1961-01-03  18.50  16.88  12.33  10.13  11.17   6.17  11.25    NaN   
3    1961-01-04  10.58   6.63  11.75   4.58   4.54   2.88   8.63   1.79   
4    1961-01-05  13.33  13.25  11.42   6.17  10.71   8.21  11.92   6.54   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
6569 1978-12-27  17.58  16.96  17.62   8.08  13.21  11.67  14.46  15.59   
6570 1978-12-28  13.21   5.46  13.46   5.00   8.12   9.42  14.33  16.25   
6571 1978-12-29  14.00  10.29  14.42   8.71   9.71  10.54  19.17  12.46   
6572 1978-12-30  18.50  14.04  21.29   9.13  12.75   9.71  18.08  12.87   
6573 1978-12-31  20.33  17.41  27.29   9.59  12.08  10.13  19.25  11.63   

        MUL    CLO    BEL    MAL  weekday  
0     10.83  12.58  18.50  15.04        6  
1      9.79   9.67  17.54  13.83        0  
2      8.50   7.67  12.75  12.71        1  
3      5.83   5.88   5.46  10.88        2  
4     10.92  10.34  12.92  11.83        3  
...     ...    ...    ...    ...      ...  
6569  14.04  14.00  17.21  40.08        2  
6570  15.25  18.05  21.79  41.46        3  
6571  14.50  16.42  18.88  29.58        4  
6572  12.46  12.12  14.67  28.79        5  
6573  11.58  11.38  12.08  22.08        6  

[6574 rows x 14 columns]

In [175]:
df['weekcheck'] = df.weekday.map(lambda x : 1 if x in [5, 6] else 0)

In [176]:
df

Yr_Mo_Dy    RPT    VAL    ROS    KIL    SHA    BIR    DUB    CLA  \
0    1961-01-01  15.04  14.96  13.17   9.29    NaN   9.87  13.67  10.25   
1    1961-01-02  14.71    NaN  10.83   6.50  12.62   7.67  11.50  10.04   
2    1961-01-03  18.50  16.88  12.33  10.13  11.17   6.17  11.25    NaN   
3    1961-01-04  10.58   6.63  11.75   4.58   4.54   2.88   8.63   1.79   
4    1961-01-05  13.33  13.25  11.42   6.17  10.71   8.21  11.92   6.54   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
6569 1978-12-27  17.58  16.96  17.62   8.08  13.21  11.67  14.46  15.59   
6570 1978-12-28  13.21   5.46  13.46   5.00   8.12   9.42  14.33  16.25   
6571 1978-12-29  14.00  10.29  14.42   8.71   9.71  10.54  19.17  12.46   
6572 1978-12-30  18.50  14.04  21.29   9.13  12.75   9.71  18.08  12.87   
6573 1978-12-31  20.33  17.41  27.29   9.59  12.08  10.13  19.25  11.63   

        MUL    CLO    BEL    MAL  weekday  weekcheck  
0     10.83  12.58  18.50  15.04        6          1  
1      9.79   9.67  17.54  13.83        0          0  
2      8.50   7.67  12.75  12.71        1          0  
3      5.83   5.88   5.46  10.88        2          0  
4     10.92  10.34  12.92  11.83        3          0  
...     ...    ...    ...    ...      ...        ...  
6569  14.04  14.00  17.21  40.08        2          0  
6570  15.25  18.05  21.79  41.46        3          0  
6571  14.50  16.42  18.88  29.58        4          0  
6572  12.46  12.12  14.67  28.79        5          1  
6573  11.58  11.38  12.08  22.08        6          1  

[6574 rows x 15 columns]

년도, 일자 상관없이 모든 컬럼의 각 달의 평균을 구하여라

In [179]:
df.groupby(df.Yr_Mo_Dy.dt.month).mean()

RPT        VAL        ROS       KIL        SHA       BIR  \
Yr_Mo_Dy                                                                   
1         14.847325  12.914560  13.299624  7.199498  11.667734  8.054839   
2         13.710906  12.111122  12.879132  6.942411  11.551772  7.633858   
3         13.158687  11.505842  12.648118  7.265907  11.554516  7.959409   
4         12.555648  10.429759  12.204815  6.898037  10.677667  7.441389   
5         11.724032  10.145619  11.550394  6.307487  10.224301  6.942061   
6         10.451317   8.949704  10.361315  5.652278   9.529926  6.410093   
7          9.992007   8.357778   9.349642  5.416935   9.302634  5.972348   
8         10.213411   8.415143   9.993441  5.270681   8.901559  5.891057   
9         11.458519   9.981002  10.756883  5.615176   9.766315  6.566222   
10        12.660610  11.010681  11.453943  6.065215  10.550251  7.159910   
11        13.200722  11.639500  12.293407  6.247611  10.501130  7.134333   
12        14.446398  12.353602  13.212276  6.829910  11.301254  7.963710   

                DUB       CLA       MUL        CLO        BEL        MAL  \
Yr_Mo_Dy                                                                   
1         11.819355  9.512047  9.543208  10.053566  14.550520  18.028763   
2         11.206024  9.341437  9.313169   9.518051  13.728898  17.156142   
3         11.310179  9.635896  9.700324  10.096953  13.810609  16.909317   
4         10.221315  8.909056  8.930870   9.158019  12.664759  14.937611   
5          8.797738  8.452903  8.040806   8.524857  12.767258  13.736039   
6          8.009556  7.920796  7.639796   7.729185  12.246407  12.861818   
7          7.843501  7.262760  7.544480   7.321416  11.676505  12.800789   
8          7.772312  6.842025  7.240573   7.002783  11.110090  12.565943   
9          8.609722  7.745677  7.610556   7.689278  12.686389  14.761963   
10         9.387778  8.726308  8.347181   8.850376  14.155323  16.697151   
11        10.814861  8.427167  8.604000   8.943167  13.815741  18.114185   
12        11.849050  9.209355  9.447258   9.627670  14.259516  18.697599   

           weekday  weekcheck  
Yr_Mo_Dy                       
1         2.989247   0.284946  
2         3.005906   0.287402  
3         3.000000   0.283154  
4         3.011111   0.288889  
5         2.982079   0.283154  
6         3.007407   0.285185  
7         3.001792   0.288530  
8         2.991039   0.283154  
9         3.009259   0.287037  
10        2.998208   0.286738  
11        2.992593   0.283333  
12        3.017921   0.288530

In [180]:
df.isnull().sum()

Yr_Mo_Dy     0
RPT          6
VAL          3
ROS          2
KIL          5
SHA          2
BIR          0
DUB          3
CLA          2
MUL          3
CLO          1
BEL          0
MAL          4
weekday      0
weekcheck    0
dtype: int64

In [182]:
df = df.fillna(method = 'ffill').fillna(method = 'bfill')

In [183]:
df.isnull().sum()

Yr_Mo_Dy     0
RPT          0
VAL          0
ROS          0
KIL          0
SHA          0
BIR          0
DUB          0
CLA          0
MUL          0
CLO          0
BEL          0
MAL          0
weekday      0
weekcheck    0
dtype: int64

RPT 컬럼의 값을 일자별 기준으로 1차차분하라

In [184]:
df['RPT'].diff()

0        NaN
1      -0.33
2       3.79
3      -7.92
4       2.75
        ... 
6569    3.75
6570   -4.37
6571    0.79
6572    4.50
6573    1.83
Name: RPT, Length: 6574, dtype: float64

RPT와 VAL의 컬럼을 일주일 간격으로 각각 이동평균한값을 구하여라

In [186]:
df[['RPT', 'VAL']].rolling(7).mean()

RPT        VAL
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
6569  11.868571   9.362857
6570  11.904286   9.595714
6571  13.017143  10.011429
6572  13.285714  10.118571
6573  14.951429  11.801429

[6574 rows x 2 columns]

서울시 미세먼지 데이터 : https://www.airkorea.or.kr/web/realSearch?pMENU_NO=97 DataUrl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv’

In [188]:
df =pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv')
df

(년-월-일:시) PM10등급  PM10 PM2.5등급  PM2.5 오존등급     오존 이산화질소등급  이산화질소  \
0     2021-05-15:15     보통  47.0      보통   19.0   좋음  0.017      좋음  0.023   
1     2021-05-15:14     보통  43.0      보통   20.0   좋음  0.024      좋음  0.019   
2     2021-05-15:13     보통  34.0      보통   24.0   보통  0.035      좋음  0.017   
3     2021-05-15:12     보통  41.0      보통   27.0   보통  0.037      좋음  0.020   
4     2021-05-15:11     보통  51.0      보통   34.0   보통  0.033      좋음  0.023   
...             ...    ...   ...     ...    ...  ...    ...     ...    ...   
1234  2021-03-25:05     보통  39.0      보통   18.0   좋음  0.026      좋음  0.025   
1235  2021-03-25:04     보통  34.0      좋음   15.0   좋음  0.017      보통  0.033   
1236  2021-03-25:03     보통  35.0      좋음   13.0   좋음  0.029      좋음  0.025   
1237  2021-03-25:02     보통  35.0      좋음   13.0   보통  0.031      좋음  0.025   
1238  2021-03-25:01     보통  42.0      좋음   13.0   좋음  0.022      보통  0.037   

     일산화탄소등급  일산화탄소 아황산가스등급  아황산가스  
0         좋음    0.4      좋음  0.003  
1         좋음    0.3      좋음  0.003  
2         좋음    0.4      좋음  0.004  
3         좋음    0.4      좋음  0.004  
4         좋음    0.4      좋음  0.005  
...      ...    ...     ...    ...  
1234      좋음    0.4      좋음  0.003  
1235      좋음    0.4      좋음  0.002  
1236      좋음    0.4      좋음  0.003  
1237      좋음    0.3      좋음  0.003  
1238      좋음    0.4      좋음  0.003  

[1239 rows x 13 columns]

일자별 영어요일 이름을 dayName 컬럼에 저장하라

In [190]:
df['(년-월-일:시)'] = pd.to_datetime(df['(년-월-일:시)'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1239 entries, 0 to 1238
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   (년-월-일:시)  1239 non-null   object 
 1   PM10등급     1233 non-null   object 
 2   PM10       1233 non-null   float64
 3   PM2.5등급    1232 non-null   object 
 4   PM2.5      1232 non-null   float64
 5   오존등급       1232 non-null   object 
 6   오존         1232 non-null   float64
 7   이산화질소등급    1232 non-null   object 
 8   이산화질소      1232 non-null   float64
 9   일산화탄소등급    1232 non-null   object 
 10  일산화탄소      1232 non-null   float64
 11  아황산가스등급    1232 non-null   object 
 12  아황산가스      1232 non-null   float64
dtypes: float64(6), object(7)
memory usage: 126.0+ KB
